### ISSUE TITLE
Scene Freezes when multiple OpenVR Sources are in Use

### ISSUE THREAD

**Issue by LonleyViper** [baffler/OBS-OpenVR-Input-Plugin#10]
Hi!

I'm trying to create a secondary scene that's more zoomed in for when I'm sniping.

I've updated the plugin and it no longer crashes when I have a second OpenVR scene, but now the active scene will freeze when I transition to it.

If I go to a different, non-vr, scene and come back it will unfreeze.

Any way to fix this?

Edit: Log file

https://hastebin.com/pijiyuxuno

**Comment by baffler** [comment]
Should be fixed with [v1.3](https://github.com/baffler/OBS-OpenVR-Input-Plugin/releases/tag/v1.3). 👍
