### ISSUE TITLE
Open VR Source never shows up in streamlabs

### ISSUE THREAD

**Issue by indiedragoncom** [baffler/OBS-OpenVR-Input-Plugin#12]
I installed the openVR plugin exactly as specified by copying the files to the C:\Program Files\Streamlabs OBS\resources\app.asar.unpacked\node_modules\obs-studio-node directory, then booting streamlabs. However, the source does not show up when I do that. I also went in to the files and checked the file path to the files that get imported through that method, and the files are confirmed in the correct locations. (like the win-openvr.dll in C:\Program Files\Streamlabs OBS\resources\app.asar.unpacked\node_modules\obs-studio-node\obs-plugins\64bit) I'm not sure what could be wrong.

**Comment by baffler** [comment]
Typically Streamlabs OBS auto-updates fine but I know I had an issue where it did stop updating. What version is it showing for you at the top in the title bar? Mine is Version: 0.11.6 and I'm able to see the OpenVR source.

**Comment by indiedragoncom** [comment]
I'm on StreamLabs OBS Version 0.11.14. I barely downloaded it right before installing the plugin because I just got a VR system

**Comment by CrayzCrinkle** [comment]
Same issue here!!

**Comment by baffler** [comment]
@indiedragoncom 
I guess my version of SLOBS wasn't auto-updating. I did manually update it and got 0.11.15 now. From what I can tell, any existing OpenVR Capture sources won't work for some reason, I have to remove the old capture in the source list, then create a new one. Have you tried that? If you don't see the OpenVR Capture source in the list when you go to add it, make sure you reinstall [v1.2 of the plugin](https://github.com/baffler/OBS-OpenVR-Input-Plugin/releases/tag/v1.2) again in
`C:\Program Files\Streamlabs OBS\resources\app.asar.unpacked\node_modules\obs-studio-node`

It's also possible 0.11.14 had broken the plugin? But I can confirm it works on 0.11.15 at least. So if you update, delete and re-add the source, make sure to reinstall the plugin, and if you're still having issues then just let me know.
