### ISSUE TITLE
New version of OpenVR

### ISSUE THREAD

**Issue by PlayroomVandals** [baffler/OBS-OpenVR-Input-Plugin#16]
I've seen that OpenVR has recently been updated, and was wondering if this plugin needs updating too.

**Comment by BOLL7708** [comment]
You mean for the merged eye views? That came in [beta 1.7.2](https://steamcommunity.com/games/250820/announcements/detail/1603764406747905854), meanwhile the lib available right now is still the [public 1.6.10](https://github.com/ValveSoftware/openvr/tree/master/headers) version. 

What is unclear at this point is if they actually updated something in the OpenVR API, or if this is a feature of the VR View client application, meaning this plugin would not have access to it. I'm sure we'll know this as soon as they publish a newer API version of OpenVR.

**Comment by baffler** [comment]
The latest OpenVR SDK seems to have the ability to do the merged eye views using the API. It would require quite a bit rewriting of the code however, since it's using an entirely different way of capturing. I'm looking into updating to this but not timeline on how long it might be.

**Comment by blackote** [comment]
Been having issues with OpenVR plugin where the FPS is stuck at 30 to 40fps.  Not sure what it is but I was able to capture at 60fps
