### ISSUE TITLE
OpenVR Capture source changes size on it's own

### ISSUE THREAD

**Issue by Rexios80** [baffler/OBS-OpenVR-Input-Plugin#19]
The source either gets bigger or smaller seemingly randomly even with the transformation locked. Is there a fix for this?

**Comment by baffler** [comment]
Haven't encountered this issue. If I can recreate it then there might be a way to fix it. Do you happen to have different custom resolutions set for different games? That could possibly be affecting the size of the capture when you switch between the games.

**Comment by baffler** [comment]
Would need more info for this. Maybe try setting the transform to "Fit to screen" instead of locking it?

**Comment by BOLL7708** [comment]
Just as a side note, for sources with dynamic sizes like this I would edit the source `Transform` and set the `Bounding Box Size` and have the contents scale to that usually with `Bounding Box Type` set to `Scale to width of bounds` or whatever is suitable. 

Regardless of their actual pixel size the source will now always match the bounding box, it has worked very well for me and is a standard feature for sources in OBS.
