### ISSUE TITLE
Linux version?

### ISSUE THREAD

**Issue by zaggynl** [baffler/OBS-OpenVR-Input-Plugin#20]
I'd be willing to test!

**Comment by baffler** [comment]
Likely not from me even though I'd like to, sorry.

**Comment by sparker256** [comment]
I am a X-Plane 11 Linux user that is currently using your OBS-OpenVR-Input-Plugin on Windows to stream VR content on Twitch. I want to migrate to Linux to do the same thing so do you think it would be possible to make a Linux version? I am willing to work on it if you think it is possible as I am a C++ plugin creator for X-Plane. Thanks Bill

**Comment by baffler** [comment]
> I am willing to work on it if you think it is possible as I am a C++ plugin creator for X-Plane. 

I think it should be possible considering the OpenVR SDK has linux binaries. I'm just not sure if you can use D3D11 with linux to get the mirror texture from OpenVR?

**Comment by Patola** [comment]
Not D3D11, linux doesn't have it native. So it would need a wrapper with wine or something. But isn't the same functionality present in Vulkan? Linux has native vulkan libraries.

**Comment by baffler** [comment]
Really just depends on how the OpenVR SDK does it on linux, it may use Vulkan for obtaining the mirror texture. I haven't looked into it at all and not sure how it does it. I just know for the windows implementation it's getting it with the D3D11 library.
