### ISSUE TITLE
Memory leak might be fixed in SteamVR beta 1.9.7

### ISSUE THREAD

**Issue by BOLL7708** [baffler/OBS-OpenVR-Input-Plugin#21]
Not sure how to message this otherwise, but figured I'll just put it here. Close and/or delete at will 😅

The [latest beta release](https://steamcommunity.com/games/250820/announcements/detail/1714113379461314416) had this point in it, which feels directly related to the memory issues described for this project 😮
> Fixed some memory leaks when VR_Init is called repeatedly in long-running applications.

**Comment by baffler** [comment]
I updated to the latest OpenVR SDK in [v1.4](https://github.com/baffler/OBS-OpenVR-Input-Plugin/releases/tag/v1.4). Thanks for the info 😃
