### ISSUE TITLE
Capture WMR overlay?

### ISSUE THREAD

**Issue by LeonxPRO** [baffler/OBS-OpenVR-Input-Plugin#23]
Hello!
Plugin don`t capture any WMR overlays, like WMR menu or Windows Desktop window inside Steam VR games. Is it issue or feature?

**Comment by baffler** [comment]
I don't use WMR, but I'm pretty sure it has it's own compositor for it's menu and other overlays. It's compositor would render over top any SteamVR, so this plugin wouldn't have access to it. If you want to make sure though, in the SteamVR menu, click "Display VR View" and see if any of your WMR menus show up there in that preview. I'm guessing it probably shouldn't.
