### ISSUE TITLE
Does not work in the latest relase of OBS 25.0.1

### ISSUE THREAD

**Issue by GingasVR** [baffler/OBS-OpenVR-Input-Plugin#24]
Does not show up as a plugin on the latest OBS release of 25.0.1

**Comment by baffler** [comment]
I'm currently on that version and haven't had the issue. If you haven't already tried, remove the plugin and reinstall with the latest version [here](https://github.com/baffler/OBS-OpenVR-Input-Plugin/releases/tag/v1.3).

If you're still having the issue, go to OBS and click File > Show Settings Folder. Navigate to "logs" folder and attach the latest txt file from there.
