### ISSUE TITLE
win_openvr_show: GetMirrorTextureD3D11 failed

### ISSUE THREAD

**Issue by csbarlas** [baffler/OBS-OpenVR-Input-Plugin#31]
Retyping this whole ticket because I looked at the log to more accurately represent my problem, but I keep getting this win_openvr_show: GetMirrorTextureD3D11 failed error no matter what. I have uninstalled and reinstalled the latest version of OBS, OpenVR Input Plugin, and launched SteamVR first and then opened OBS but no luck. Followed about 3 installation guides and have done the install over maybe 3 times. Any help?

**Comment by baffler** [comment]
Which version have you tried? Might be a long shot, but try v1.3 if you haven't.
