### ISSUE TITLE
If I'm running stream VR without an HMD attached OBS seems to crash when the source is set to visible.

### ISSUE THREAD

**Issue by black-light-studio** [baffler/OBS-OpenVR-Input-Plugin#38]
So when I'm running steam VR without my HMD running, OBS will crash if I switch to a scene where this plugin is set to visible.
I'm doing this when playing non-VR games, so I can use my trackers for SUVA. 
I can work around the issue by not accidentally selecting a scene with the plugin in, but it can be risky if streaming and just accidentally crashing OBS
[Crash 2020-08-15 18-57-49.txt](https://github.com/baffler/OBS-OpenVR-Input-Plugin/files/5079178/Crash.2020-08-15.18-57-49.txt)

**Comment by baffler** [comment]
Are you using [this method](https://github.com/Guribo/SUVA/wiki/Instruction-for-usage-of-SUVA-with-Trackers-but-without-a-VR-Headset) to setup steamVR without a HMD?

**Comment by black-light-studio** [comment]
> Are you using [this method](https://github.com/Guribo/SUVA/wiki/Instruction-for-usage-of-SUVA-with-Trackers-but-without-a-VR-Headset) to setup steamVR without a HMD?

I wasn't, and that did help it to not crash in that scenario thanks.
