### ISSUE TITLE
obs wont start anymore this is malware

### ISSUE THREAD

**Issue by mr2meowsYT** [baffler/OBS-OpenVR-Input-Plugin#40]

**Comment by BOLL7708** [comment]
That's a fairly serious accusation.

**Comment by Blumlaut** [comment]
it's open source, if its malware someone sure would've noticed, don't you think?

**Comment by baffler** [comment]
If OBS isn't starting you could paste some logs to show the issue. It's probably just an issue with not copying all the required files needed for the plugin.
