### ISSUE TITLE
[Feature request] Add support for changing scene with a button on the vr controllers

### ISSUE THREAD

**Issue by tompointexe** [baffler/OBS-OpenVR-Input-Plugin#41]
Hi, i'm looking for a manner to control obs with a button press on my controller, buy i havn't find any tool for that.
Thanks for looking into this feature request

**Comment by BOLL7708** [comment]
Not stopping anyone from adding this to this plugin, but as an alternative I made [a tool](https://github.com/BOLL7708/OpenVR2Key) to trigger global hotkeys with controllers. Right now only comes with Index bindings as that's what I use, but it should be possible to add new ones, if the SteamVR input UI co-operates.

**Comment by tompointexe** [comment]
Ok i'l take a look :) thanks
