### ISSUE TITLE
HTC Vive crop not correct with latest SteamVR

### ISSUE THREAD

**Issue by BOLL7708** [baffler/OBS-OpenVR-Input-Plugin#5]
I saw in the [update notes](https://steamcommunity.com/gid/103582791435040972/announcements/detail/1723075465333731957) for SteamVR (2018-07-26) that the render mask for the HTC Vive has been updated, which gives me a different size output and the crop setting for it shows a black corner or two. 

> Improved hidden area mesh for Vive and Vive Pro. Vive saves an additional 3% of rendering, and Vive Pro saves an additional 7% of rendering.

The full size of the source I get is 1724 x 1915, which to me sounds bigger than before, but now I'm not sure. (Edit: found my old values which was 1512 x 1680, and I have no SS settings, will that change the output size?!)

**Update**: checking out the uncropped version it's not a surprise, they have adjusted the mask to match the cut of the optics, making space for the nose.
![obs64_2018-07-27_00-57-21](https://user-images.githubusercontent.com/12276837/43293109-d54b1714-9138-11e8-8db4-e730ab7a713e.png)

**Comment by baffler** [comment]
Very late, but do you have the updated values to use for this? I can update the crop presets with it.

**Comment by BOLL7708** [comment]
Ah, in this time I've actually upgraded to the Valve Index, sorry! 😅

**Comment by baffler** [comment]
No worries, I may just dust off my vive and figure out good values 😀
