### ISSUE TITLE
Vive Wireless

### ISSUE THREAD

**Issue by KitBallard64** [baffler/OBS-OpenVR-Input-Plugin#9]
So I recently picked up the wireless adapter for my Vive and after I got it set up, I went to turn on Streamlabs OBS like I usually do. It crashes without an error. I thought it was som'in I did so I reinstalled everything I knew and kept trying. It kept crashing. I just tried to plug my headset back in to test som'in and and since I was crashing with Playspace Mover,  I tried Mover again and it's working. So I poked the Mover's page and there's an update that fixed the crash, so I figured I should maybe say som'in here, as it's affecting this app too.

~Kit

**Comment by baffler** [comment]
I have the wireless adapter as well. I can't seem to reproduce this. I don't use Playspace Mover so I'm not sure if that would cause the issue, but no crash in regular OBS or SLOBS while using Vive wirelessly. Any other steps you might have left out I could try, like a specific game or something?

**Comment by KitBallard64** [comment]
huh... weird. it's now sort of working. Sorry to trouble you with this. But som'in does bring up my attention and I'll post it on another topic.
